### ISSUE TITLE
save does not committing when using pool

### ISSUE THREAD

**Issue by ftamy9** [altairbow/django-db-connection-pool#33] opened 2022-05-09 09:57 UTC
Thanks @altairbow , I have same problem. 
  I can not save correctly. the program looks ok without error but the table is not update when I check it on django admin. It works ok when I use (('ENGINE': 'django.db.backends.oracle')) with out the pool.

Python3.8.10 + django 3.2 + Oracle 18C

 'default': {
        'ENGINE': 'dj_db_conn_pool.backends.oracle',
        'POOL_OPTIONS': {
            'POOL_SIZE': 10,
            'MAX_OVERFLOW': 10,
            'RECYCLE': 24 * 60 * 60,
        },
        'AUTOCOMMIT': True,
        'NAME': 'xxx',
        'USER': 'xxx',
        'PASSWORD': 'xxx',
    }`
`

_Originally posted by @boscharun in https://github.com/altairbow/django-db-connection-pool/issues/5#issuecomment-494926473_

**Comment by kevin-kessler** [comment] 2022-06-28 17:17
Same issue here. Any idea @altairbow ?

**Comment by kevin-kessler** [comment] 2022-06-29 17:21
So it looks like the Oracle connections created with SQLAlchemy (which django-db-connection-pool is based on) have their autocommit flag set to 0 by default. 

A quick test of setting the flag to 1 after the connection has been returned by the pool confirmed the assumption and Django started persisting my changes all of a sudden again.

You can try it yourself by setting the flag in mixins.py of the django-db-connection-pool module.
Line 75 onwards:
`# get one connection from the pool
  conn = db_pool.connect()
  logger.debug(_("got %s's connection from its pool"), self.alias)
  conn.connection.autocommit=1
  return conn`

Careful: the connection object depends on the database backend that you are using and this autocommit attribute might not be available if the connection object is created via a different backend (i.e. different from oracle_cx).

**Comment by altairbow** [comment] 2022-06-30 10:25
> So it looks like the Oracle connections created with SQLAlchemy (which django-db-connection-pool is based on) have their autocommit flag set to 0 by default.
> 
> A quick test of setting the flag to 1 after the connection has been returned by the pool confirmed the assumption and Django started persisting my changes all of a sudden again.
> 
> I fixed it by implementing _set_autocommit in oracle/base.py and submitted a pullrequest here: #35

Great work! Thansk, PR has been merged, and version 1.2.0 has been released.

**Comment by kevin-kessler** [comment] 2022-06-30 13:16
> Great work! Thanks, PR has been merged, and version 1.2.0 has been released.

Perfect, thanks for the quick action!

**Closed** 2022-10-28 06:59 UTC
