### ISSUE TITLE
django startup error (environment: python(v3.8) django(v4.0) pymysql(v1.0.2) django-db-connection-pool(v1.0.7))

### ISSUE THREAD

**Issue by skotori** [altairbow/django-db-connection-pool#26] opened 2021-12-24 07:35 UTC
File "...\lib\site-packages\django\db\utils.py", line 122, in load_backend
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: 'dj_db_conn_pool.backends.mysql' isn't an available database backend or couldn't be imported. Check the above exception. To use one of the built-in backends, use 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'

**Comment by skotori** [comment] 2021-12-24 07:50
the django-db-connection-pool is installed by 'pip install django-db-connection-pool'

**Comment by altairbow** [comment] 2021-12-24 13:48
Has django-db- connection-pool been installed yet?

**Comment by skotori** [comment] 2021-12-27 02:27
> Has django-db- connection-pool been installed yet?

yes

**Comment by skotori** [comment] 2021-12-27 02:32
> Has django-db- connection-pool been installed yet?

[![TBCXCD.png](https://s4.ax1x.com/2021/12/27/TBCXCD.png)](https://imgtu.com/i/TBCXCD)

**Comment by skotori** [comment] 2022-01-04 07:35
Maybe Django 4.0 changed the database backends API.What is the latest version of Django based on

**Comment by skotori** [comment] 2022-01-04 09:06
Django started after it was lowered from 4.0 to 3.2.Are there plans to support Django version 4.0

**Comment by altairbow** [comment] 2022-01-05 01:11
> Django started after it was lowered from 4.0 to 3.2.Are there plans to support Django version 4.0

Caused by [Deprecate ugettext(), ugettext_lazy(), ugettext_noop(), ungettext(), and ungettext_lazy()](https://code.djangoproject.com/ticket/30165), I will fix it soon

**Comment by altairbow** [comment] 2022-01-05 01:44
`ImproperlyConfigured` has been fixed in  [django4_support](https://github.com/altairbow/django-db-connection-pool/tree/django4_support) branch, You can test it in your case.

**Comment by skotori** [comment] 2022-01-05 02:57
installed the django4_support branch by 'pip install git+https://github.com/altairbow/django-db-connection-pool.git@django4_support', start normally in Django 4.0 environment

**Comment by skotori** [comment] 2022-01-05 03:08
There is a problem. I don't know if it's because of my code. Start 100 threads to execute database insert, and the code will be stuck after execution for a period of time.

**Comment by skotori** [comment] 2022-01-05 03:13
The length of time the code runs before it gets stuck is proportional to POOL_SIZE.

**Comment by skotori** [comment] 2022-01-05 03:39
My configuration is "'POOL_OPTIONS': { 'POOL_SIZE': 10, 'MAX_OVERFLOW': 10, 'RECYCLE': 24 * 60 * 60 }". Is it because threads do not share a connection, and then the connection expires too long, resulting in thread blocking.

**Comment by altairbow** [comment] 2022-01-12 07:55
Has [conn.close](https://github.com/altairbow/django-db-connection-pool/blob/master/dj_db_conn_pool/core/mixins.py#L88) been called after your thread done it's work?

**Comment by skotori** [comment] 2022-01-13 03:38
> Has [conn.close](https://github.com/altairbow/django-db-connection-pool/blob/master/dj_db_conn_pool/core/mixins.py#L88) been called after your thread done it's work?

No, the connection is not closed.

**Comment by altairbow** [comment] 2022-01-13 06:40
You should call ```conn.close``` to release the connection

**Comment by skotori** [comment] 2022-01-13 07:25
> You should call `conn.close` to release the connection

But I use Django's ORM, MODEL method.

**Comment by altairbow** [comment] 2022-01-20 07:35
Django close all database connections automatically after ```django.core.signals.request_finished```  received, means Django won't release database connection before your

**Comment by altairbow** [comment] 2022-01-20 07:45
Django close all database connections automatically after ```django.core.signals.request_finished``` received, means Django won't release database connection before your threads finish, don't start too many threads for single user request, it's not a good idea in web development, If it's a background task, you have two option: 1. Increase MAX_OVERFLOW or POOL_SIZE 2. in your code，call conn.close() to release database connection to pool

**Comment by altairbow** [comment] 2022-01-20 07:51
fixed by #27

**Closed by altairbow** 2022-01-20 07:51 UTC
Labels: bug

**Comment by skotori** [comment] 2022-01-21 06:50
ok, thank you.

**Comment by imperio59** [comment] 2022-04-03 18:46
Can we get a new release with this fix in? 1.0.7 does not contain this fix.

**Comment by altairbow** [comment] 2022-04-06 02:22
> Can we get a new release with this fix in? 1.0.7 does not contain this fix.

1.1.0 has been released.
